export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const RESET_PRODUCT_INFO = 'RESET_PRODUCT_INFO';
export const RESET_USER_INFO = 'RESET_USER_INFO';
